security.basic.enabled: false
spring.thymeleaf.mode: LEGACYHTML5

spring:
  profiles.active: test

server:
  port: 9020
  session:
    timeout: 1800 # session timeout in second
    cookie.max-age: 1800