spring:
  datasource:
    jdbc-url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    maximum-pool-size: 1
    validationQuery: SELECT 1
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /consoleta
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true